### ISSUE TITLE
Add Account Linking Readme

### ISSUE THREAD

**Issue by TheDreamSaver** [RocketChat/alexa-rocketchat#10]
Add a readme for describing how we can add account linking to the skill.

Feel free to add/update the setup instructions in readme @PrajvalRaval @acerbisgianluca if you find anything missing while setting up the account linking on your end.
If all works fine, will close the issue.

**Comment by acerbisgianluca** [comment]
I followed the istructions and all works fine, so I think you can close this issue.

**Comment by PrajvalRaval** [comment]
Yeah not an issue anymore
