### ISSUE TITLE
[BEGINNER] Add More Real Life Chat Example's To Slot Values

### ISSUE THREAD

**Issue by PrajvalRaval** [RocketChat/alexa-rocketchat#33]
We have created a lot of locales for our skill but to make Alexa understand your command better we need to add more and more examples to slot values. Especially in message slot, since it is the one that has the most variety in every locale.

**Comment by acerbisgianluca** [comment]
For example, this one should be labeled with `BEGINNER` tag. Meanwhile you can add it in the issue title.

**Comment by PrajvalRaval** [comment]
> For example, this one should be labeled with `BEGINNER` tag. Meanwhile you can add it in the issue title.

Cannot create a new label called BEGINNER, @Sing-Li Can you create one. I am using text as a placeholder till it is done.
