### ISSUE TITLE
User's name not being spoken in some cases

### ISSUE THREAD

**Issue by TheDreamSaver** [RocketChat/alexa-rocketchat#39]
In **GetLastMessageFromChannelIntent** sometimes the name of the user isn't present in the response.

Ideally, in the below example it should say, _Ashish Jha says, hi._
But the actual result is, _says, hi._

![](https://i.ibb.co/hWN8vZd/Issue7.jpg)

**Comment by PrajvalRaval** [comment]
Fixed This Issue in PR #40

**Comment by TheDreamSaver** [comment]
Thank you.
